- name: Deploy Everything
  hosts: testServers
  become: true
  vars_files:
    - vault.yaml
  tasks:
    - name: Add the user 'hillel' with sudo privileges
      ansible.builtin.user:
        name: hillel
        comment: Hillel Technical User
        group: sudo
        password: "{{ default_password  | password_hash('sha512') }}"
        update_password: "on_create"

    - name: Install software set
      ansible.builtin.apt:
        state: present
        update_cache: yes
        name:
          - nginx
          - gzip
          - git

    - name: Run services
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes